### ISSUE TITLE
JIRA state does not exist or no transition possible

### ISSUE THREAD

**Issue by gustonator** [prometheus-community/jiralert#115]
Hi,
When sending a test alert with:
```
curl -H "Content-type: application/json" -X POST \
  -d '{"receiver": "jira-in", "status": "firing", "alerts": [{"status": "firing", "labels": {"alertname": "TestAlert", "key": "value"} }], "groupLabels": {"alertname": "TestAlert"}}' \
  http://localhost:9097/alert
```

i'm getting the error: 
```
{"Error":true,"Status":500,"Message":"JIRA state \"In Progress\" does not exist or no transition possible for IN-55245"}
```
which is weird, because the state exists (tried also with "To Do" but no luck), but also it tries to edit/update an already existing jira ticket as you see in the error message. but this ticket was create before with zabbix, and is related to something completely different.

my container config is: 
```
    spec:
      containers:
      - args:
        - -log.level=debug
        - -log.format=json
        - -hash-jira-label
        - -config=/opt/jiralert/config/jiralert.yml
        command:
        - /bin/jiralert
        image: czdcm-quay.lx.ifortuna.cz/openshift/jiralert:1.1
```
and jiralert config:

```
  jiralert.tmpl: |
    {{ define "jira.summary" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}

    {{ define "jira.description" }}{{ range .Alerts.Firing }}Labels:
    {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}
    Annotations:
    {{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}
    Source: {{ .GeneratorURL }}
    {{ end }}{{ end }}
  jiralert.yml: |
    # Global defaults, applied to all receivers where not explicitly overridden. Optional.
    defaults:
      # API access fields.
      api_url: https://jira-t.myfortuna.eu
      user: <jira api user>
      password: <jira api pass>
      # The type of JIRA issue to create. Required.
      issue_type: Incident
      # Issue priority. Optional.
      priority: Critical
      # Go template invocation for generating the summary. Required.
      summary: '{{ template "jira.summary" . }}'
      # Go template invocation for generating the description. Optional.
      description: '{{ template "jira.description" . }}'
      # State to transition into when reopening a closed issue. Required.
      reopen_state: "In Progress"
      # Do not reopen issues with this resolution. Optional.
      wont_fix_resolution: "Won’t Fix"
      # Amount of time after being closed that an issue should be reopened, after which, a new issue is created.
      # Optional (default: always reopen)
      reopen_duration: 0h

    # Receiver definitions. At least one must be defined.
    receivers:
        # Must match the Alertmanager receiver name. Required.
      - name: 'jira-in' 
        project: IN
        issue_type: Incident
        # Copy all Prometheus labels into separate JIRA labels. Optional (default: false).
        add_group_labels: false
        fields:
          customfield_17254: '108' # = AOB-PM  # mandatory field for incidents

    # File containing template definitions. Required.
    template: /opt/jiralert/config/jiralert.tmpl
```

Can anyone help with this?
