### ISSUE TITLE
add the possibility to choose custom fields when ticket is resolved

### ISSUE THREAD

**Issue by gustonator** [prometheus-community/jiralert#118]
Hi,
When there are custom required fields in jira, the ticket is not auto closed - transitioned. 
only the summary (ticket name) is  changed from `FIRING:x` to `RESOLVED`

```
{"caller":"template.go:90","level":"debug","msg":"template output","output":"[RESOLVED] [TEST] ocpbackup-BackuperIsRunningRegularly","ts":"2022-06-07T06:43:40.737948419Z"}
{"caller":"template.go:69","level":"debug","msg":"executing template","template":"{{ template \"jira.description\" . }}","ts":"2022-06-07T06:43:40.737970281Z"}
{"caller":"template.go:90","level":"debug","msg":"template output","output":"\n","ts":"2022-06-07T06:43:40.738003119Z"}
{"caller":"notify.go:338","description":"\n","key":"IN-137447","level":"debug","msg":"updating issue with new description","ts":"2022-06-07T06:43:40.738018325Z"}

{"caller":"main.go:174","err":"JIRA state \"In Progress\" does not exist or no transition possible for IN-137447","groupLabels":{"alertname":"ocpbackup-BackuperIsRunningRegularly","env":"TEST"},"level":"error","msg":"error handling request","receiver":"jira-minor","statusCode":500,"statusText":"Internal Server Error","ts":"2022-06-07T06:43:39.981231999Z"}
```

please add the possibility to choose custom required fields and adding a comment for self resolution like it is during ticket creation.

something like this: 
```
        create_fields:
            assignee: { "name": "<user>" }
            customfield_17254: '108' 
            customfield_22117: { "id": "23924" }
            customfield_22118: { "id": "23926" }
            
        resolve_fields:
            customfield_xxxxx: { "value": "this is an autoclose comment" }
            customfield_xxxxx: { "id": "23926" }
```

thanks
