### ISSUE TITLE
Summary can't exceed 255 characters

### ISSUE THREAD

**Issue by east4ming** [prometheus-community/jiralert#123]
When using jiralert, there are lots of these errors: "Summary can't exceed 255 characters"
![image](https://user-images.githubusercontent.com/13358726/182278211-f04c2a69-1550-48bb-b495-3d8067c69ef6.png)

My Jiralert Flags:
```yaml
...
          args:
            - '--config=/jiralert-config/jiralert.yml'
            - '--log.level=debug'
            - '--listen-address=:9097'
            - '--hash-jira-label=true'
```

My Jiralert config:

```yaml
template: jiralert.tmpl
defaults:
  api_url: https://example.atlassian.net
  user: xxx
  password: 'xxx'
  issue_type: Support
  priority: High
  summary: '{{ template "jira.summary" . }}'
  description: '{{ template "jira.description" . }}'
  reopen_state: 'Back to in progress'
  wont_fix_resolution: "Won't Do"
  reopen_duration: 30d

receivers:
  - name: 'jiralert'
    project: ICS
    add_group_labels: false
    auto_resolve:
      state: 'Resolve this issue'
```
    
My Template:

```
{{ define "jira.summary" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}

{{ define "jira.description" }}{{ range .Alerts.Firing }}Labels:
{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
{{ end }}

Annotations:
{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}
{{ end }}

Source: {{ .GeneratorURL }}
{{ end }}

CommonLabels:
{{ range .CommonLabels.SortedPairs }} - {{ .Name }} = {{ .Value}}
{{ end }}

GroupLabels:
{{ range .GroupLabels.SortedPairs }} - {{ .Name }} = {{ .Value}}
{{ end }}
{{ end }}
```

Thanks.
