### ISSUE TITLE
not able to fill customfield_10002 from alert label value

### ISSUE THREAD

**Issue by amed005** [prometheus-community/jiralert#136]
Hi, i want to fill the customfield_10002 (organization id) with the value of an alert label but i had no luck so far.

**jiralert-configmap**
```
    # Receiver definitions. At least one must be defined.
    receivers:
        # Must match the Alertmanager receiver name. Required.
      - name: 'xxx'
        project: "{{ .CommonLabels.projectkey }}"
        add_group_labels: false
        fields:
          "customfield_10147": { "value": "{{ .CommonLabels.environment }}" }
          "customfield_10002": [322]
```

Inserting the value like in the example above works and displays the organization correctly inside the jira ticket.

But when using a variable like this:
`          "customfield_10002": [ {{ .CommonLabels.organizationid }} ]`
an error is thrown at start of jiralert:
level=error ts=2022-11-08T16:09:07.701670386Z caller=main.go:76 msg="error loading configuration" path=config/jiralert.yml err="yaml: invalid map key: map[interface {}]interface {}{\".CommonLabels.organizationid\":interface {}(nil)}"

Any ideas? i cant get this working, not matter what i try.
