### ISSUE TITLE
doTransition gives inaccurate log message on failure

### ISSUE THREAD

**Issue by nlgotz** [prometheus-community/jiralert#175]
When trying to auto-resolve an alert, I was getting the message

```bash
Jira state \"Reopen\" does not exist or no transition possible for <ISSUE>
```

The following was my config:

```yaml
---
defaults:
  api_url: http://jira:8080
  user: jiralert
  password: 'JIRAlert'
  issue_type: Incident
  priority: Highest
  summary: '{{ template "jira.summary" . }}'
  description: '{{ template "jira.description" . }}'
  reopen_state: Reopen
  wont_fix_resolution: ""
  reopen_duration: 1h
receivers:
  - name: 'jira'
    project: SERVICE
    auto_resolve:
        state: 'DONE'

template: jiralert.tmpl
```

It looks like the error returned is using the wrong variable `r.conf.ReopenState` instead of `transitionState` as used throughout the rest of the function
