### ISSUE TITLE
Filter alerts that create JIRA

### ISSUE THREAD

**Issue by esegcy** [prometheus-community/jiralert#52]
This is a feature request.
Could you please add an option to filter alerts that should and should-not create alerts?
For example, for the following alerts:
```
 Alert: FirstAlert - warning
 Cluster:  aaa
 Description:
 Runbook: <|:spiral_note_pad:>
 Details:
  • alertname: first example alert
  • prometheus: monitoring/prometheus-prometheus-oper-prometheus
  • severity: warning
 
 Alert: SecondAlert - critical
 Cluster:  aaa
 Description: 
 Runbook: <|:spiral_note_pad:>
 Details:
  • alertname: second example alert
  • prometheus: monitoring/prometheus-prometheus-oper-prometheus
  • severity: critical
```

I only want a JIRA issue created for `severity: critical` alert, and _not_ for the `severity: warning`.
Could you help with this?

**Comment by mxey** [comment]
@esegcy This is something you configure in Alertmanager, not in a receiver.

```yaml
receivers:
  - name: "null"
  - name: jira
    webhook_configs:
      - url: "http://jiralert/alert"
        send_resolved: false

route:
  receiver: "null"
  routes:
    - match:
        severity: critical
      receiver: jira
```
