### ISSUE TITLE
Update issue title and description when reopening

### ISSUE THREAD

**Issue by mbode** [prometheus-community/jiralert#9]
It would be nice if the summary and description of an issue that had been closed before and is now reopened would be updated. The summary could just be replaced, whereas appending the new content with some sort of separator might be useful for the description.

**Comment by InKolev** [comment]
@mbode , @charlspjohn , Guys, I know it's not entirely related to this issue, but can you give me more details how you achieved reopening, because I can't seem to make Jiralert to re-open an existing issue.

I have the following scenario: 

1. Jiralert receives an alert and opens the issue in Jira with description and stuff (all good).
2. A person picks the Jira issue, resolves it, and updates the status to "Completed"/"Done".
3. Jiralert receives the same alert again, **but doesn't re-open the issue** (it doesn't do anything in this case), although I have the reopen_state clearly defined in the config.

This is my Jiralert configuration:

```
# Global defaults, applied to all receivers where not explicitly overridden. Optional.
defaults:
  # API access fields.
  api_url: https://{myOrg}.atlassian.net
  user: {myUser}
  password: {myPass}

  # The type of JIRA issue to create. Required.
  issue_type: Task
  # Issue priority. Optional.
  priority: Critical
  # Go template invocation for generating the summary. Required.
  summary: '{{ template "jira.summary" . }}'
  # Go template invocation for generating the description. Optional.
  description: '{{ template "jira.description" . }}'
  # State to transition into when reopening a closed issue. Required.
  reopen_state: "In Progress"
  # Do not reopen issues with this resolution. Optional.
  wont_fix_resolution: "Won't Fix"

# Receiver definitions. At least one must be defined.
receivers:
    # Must match the Alertmanager receiver name. Required.
  - name: 'jira-ab'
    # JIRA project to create the issue in. Required.
    project: DP
    # Copy all Prometheus labels into separate JIRA labels. Optional (default: false).
    add_group_labels: false
# File containing template definitions. Required.
template: jiralert.tmpl
```

I also checked if a transition from "Completed" to "In Progress" for this Issue is possible at this url:
https://{myOrg}.atlassian.net//rest/api/2/issue/{issueId}?expand=transitions
And it returns that it's possible.

Any ideas what might be causing this, would be very helpful.

Thanks in advance.
