### ISSUE TITLE
Field 'summary' cannot be set. It is not on the appropriate screen, or unknown.

### ISSUE THREAD

**Issue by bumarcell** [prometheus-community/jiralert#95]
Hello friends :)

I have Jiralert deployed in Kubernetes and creating tickets on a locally hosted Jira server.
At the moment Jiralert is working but it's not creating tickets for all alerts it's receiving. I checked the logs and I found out that one of the errors I'm getting is happening when Jiralert is trying to update issue with new summery.
Error:
`caller=notify.go:382 msg=handleJiraErrResponse api=Issue.UpdateWithOptions err="summary - Field 'summary' cannot be set. It is not on the appropriate screen, or unknown.: request failed. Please analyze the request body for more details.`
First thing I tried was to add the field Summary to the screen used for **Reopen** event in Jira, but this didn't work unfortunately. 

Could you please give me a hint on how to solve this issue? 
How is it possible to analyze the request body for more details?

Best regards
Jamal

P.S. Another error I'm getting is `groupLabels="unsupported value type"`. I tried changing the log format to JSON but unfortunately it didn't work. Would be great if I could get an insite on how to solve this as well!

**Comment by gustonator** [comment]
Hi @bumarcell , If you trying to create an incicident (IN) or  check the page in jira, if you use the field 'summary'. 
the error 'It is not on the appropriate screen' means, that you are trying to write into a field which is not used on the page, or does not exist.  Or maybe you changed the summary field, and using a custom field for it. 
In my jira I have following custom fields which are mandatory: 

```
      fields:
          customfield_17254: '108'                   # project -  AOB-PM
          customfield_21801: { "id": "23206" }       # Impact (23207[Low], 23206[Medium], 23200[High])
          customfield_21803: { "id": "23217" }       # Urgency (23220[Low], 23217[Medium], 23215[High])
          customfield_22304: { "id": "23705" }       # Compliance/GDPR/AML/RG (23704[Yes], 23705[No])
```
the error 'groupLabels="unsupported value type"' is because you are sending thi value to the non-existing field.
